InternoteNoteBundle:
    resource: "@InternoteNoteBundle/Resources/config/routing.yml"
    prefix:   /

NerdHerdHelloBundle:
    resource: "@NerdHerdHelloBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
