NerdHerdHelloBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: NerdHerdHelloBundle:Default:index }

hello:
    pattern:  /hellothere/{name}
    defaults: { _controller: NerdHerdHelloBundle:Hello:index }