NerdHerdHelloBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: NerdHerdHelloBundle:Default:index }

helloThere:
    pattern:  /hellothere/{name}
    defaults: { _controller: NerdHerdHelloBundle:HelloThere:index }