_welcome:
    pattern: /
    defaults: { _controller: NerdHerdHelloBundle:Main:welcome }

NerdHerdHelloBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: NerdHerdHelloBundle:Default:index }

helloThere:
    pattern:  /hellothere/{name}
    defaults: { _controller: NerdHerdHelloBundle:HelloThere:index }
    
productForm:
    pattern: /productForm/
    defaults: { _controller: NerdHerdHelloBundle:FormTest:new }
    
product_new:
    pattern: /productForm/
    defaults: { _controller: NerdHerdHelloBundle:FormTest:new }